"""Markdown report renderer for session autopsy.

Takes the 4 analysis results and produces a complete Markdown string.
"""

from __future__ import annotations

from aide.autopsy.analyzer import (
    ContextAnalysis,
    CostAnalysis,
    SessionSummary,
    SuggestionsReport,
)


def render_report(
    summary: SessionSummary,
    cost: CostAnalysis,
    context: ContextAnalysis,
    suggestions: SuggestionsReport,
) -> str:
    """Render full autopsy report as Markdown."""
    sections = [
        _render_header(summary),
        _render_summary(summary),
        _render_cost(cost),
        _render_context(context),
        _render_suggestions(suggestions),
        "\n---\n*Generated by aide autopsy · zero LLM calls*\n",
    ]
    return "\n".join(sections)


def _format_duration(seconds: int | None) -> str:
    """Format duration in human-readable form."""
    if not seconds:
        return "\u2014"
    h, remainder = divmod(seconds, 3600)
    m = remainder // 60
    if h > 0:
        return f"{h}h {m}m"
    return f"{m}m" if m > 0 else "<1m"


def _format_tokens(tokens: int) -> str:
    """Format token count with K/M suffix for readability."""
    if tokens >= 1_000_000:
        return f"{tokens / 1_000_000:.1f}M"
    if tokens >= 1_000:
        return f"{tokens / 1_000:.1f}K"
    return str(tokens)


def _render_header(summary: SessionSummary) -> str:
    """Render report header with session metadata."""
    short_id = summary.session_id[:8]
    date = summary.started_at[:10] if summary.started_at else "unknown"
    duration = _format_duration(summary.duration_seconds)

    lines = [
        f"# Session Autopsy: `{short_id}`",
        "",
        "| Field | Value |",
        "|-------|-------|",
        f"| **Project** | {summary.project_name} |",
        f"| **Date** | {date} |",
        f"| **Duration** | {duration} |",
        f"| **Cost** | ${summary.estimated_cost_usd:.2f} |",
        "",
    ]
    return "\n".join(lines)


def _render_summary(summary: SessionSummary) -> str:
    """Render Section 1: Session Summary."""
    lines = [
        "## 1. Session Summary",
        "",
        "| Metric | Value |",
        "|--------|-------|",
        f"| Messages | {summary.message_count} "
        f"({summary.user_message_count} user, "
        f"{summary.assistant_message_count} assistant) |",
        f"| Tool calls | {summary.tool_call_count} |",
        f"| Input tokens | {_format_tokens(summary.total_input_tokens)} |",
        f"| Output tokens | {_format_tokens(summary.total_output_tokens)} |",
        f"| Cache read | {_format_tokens(summary.total_cache_read_tokens)} |",
        f"| Cache creation | {_format_tokens(summary.total_cache_creation_tokens)} |",
        "",
    ]

    # Tool breakdown inline
    if summary.tool_breakdown:
        tools_str = ", ".join(
            f"{t.tool_name} ({t.count})" for t in summary.tool_breakdown
        )
        lines.append(f"**Tools used:** {tools_str}")
        lines.append("")

    # Files modified
    if summary.files_modified:
        lines.append("**Files modified:**")
        for f in summary.files_modified:
            lines.append(f"- `{f}`")
        lines.append("")

    # Files read
    if summary.files_read:
        lines.append("**Files read:**")
        for f in summary.files_read:
            lines.append(f"- `{f}`")
        lines.append("")

    return "\n".join(lines)


def _render_cost(cost: CostAnalysis) -> str:
    """Render Section 2: Cost Analysis."""
    lines = [
        "## 2. Cost Analysis",
        "",
        f"**Total cost:** ${cost.total_cost_usd:.2f}",
        "",
        "### Cost by Category",
        "",
        "| Category | Input | Output | Cost | % |",
        "|----------|-------|--------|------|---|",
    ]

    for cat in cost.categories:
        if cat.estimated_cost_usd > 0 or cat.input_tokens > 0 or cat.output_tokens > 0:
            lines.append(
                f"| {cat.category} | {_format_tokens(cat.input_tokens)} | "
                f"{_format_tokens(cat.output_tokens)} | "
                f"${cat.estimated_cost_usd:.2f} | {cat.percentage:.1f}% |"
            )

    lines.append("")

    # Cache efficiency
    ce = cost.cache_efficiency
    lines.append("### Cache Efficiency")
    lines.append("")
    lines.append(
        f"Cache hit rate: **{ce.cache_hit_rate:.0%}** | "
        f"Cache savings: **${ce.cache_savings_usd:.2f}** | "
        f"Fresh input: {_format_tokens(ce.fresh_input_tokens)} | "
        f"Cache read: {_format_tokens(ce.cache_read_tokens)} | "
        f"Cache creation: {_format_tokens(ce.cache_creation_tokens)}"
    )
    lines.append("")

    # Top 5 expensive turns
    if cost.most_expensive_turns:
        lines.append("### Most Expensive Turns")
        lines.append("")
        lines.append("| Turn | Role | Tools | Context | Output | Cost |")
        lines.append("|------|------|-------|---------|--------|------|")
        for turn in cost.most_expensive_turns:
            tools = turn.tool_names or "\u2014"
            context_tokens = (
                turn.input_tokens + turn.cache_read_tokens + turn.cache_creation_tokens
            )
            lines.append(
                f"| {turn.turn_number} | {turn.role} | {tools} | "
                f"{_format_tokens(context_tokens)} | "
                f"{_format_tokens(turn.output_tokens)} | "
                f"${turn.estimated_cost_usd:.2f} |"
            )
        lines.append("")

    return "\n".join(lines)


def _render_context_curve(context: ContextAnalysis) -> str:
    """Render ASCII bar chart of context utilization."""
    if not context.context_curve:
        return "No context data available."

    curve = context.context_curve
    peak = context.peak_context_tokens

    if peak == 0:
        return "No context data available."

    # Sample ~15 points from the curve
    total_points = len(curve)
    if total_points <= 15:
        sampled = curve
    else:
        step = max(1, total_points // 15)
        sampled = [curve[i] for i in range(0, total_points, step)]
        # Always include the last point
        if sampled[-1] != curve[-1]:
            sampled.append(curve[-1])

    # Compaction turn numbers for marking
    compaction_turns = {e.turn_number for e in context.compaction_events}

    bar_width = 20
    lines = []
    for point in sampled:
        ratio = point.cumulative_input_tokens / peak if peak > 0 else 0
        filled = int(ratio * bar_width)
        bar = "\u2588" * filled + "\u2591" * (bar_width - filled)
        marker = " \u2190 compaction" if point.turn_number in compaction_turns else ""
        lines.append(
            f"Turn {point.turn_number:>3}: {bar} "
            f"{_format_tokens(point.cumulative_input_tokens)}{marker}"
        )

    return "\n".join(lines)


def _render_context(context: ContextAnalysis) -> str:
    """Render Section 3: Context Analysis."""
    lines = [
        "## 3. Context Analysis",
        "",
        "| Metric | Value |",
        "|--------|-------|",
        f"| Peak context | {_format_tokens(context.peak_context_tokens)} |",
        f"| Context utilization | {context.context_utilization_pct:.0%} of 200K |",
        f"| Avg input/turn | {_format_tokens(context.avg_input_tokens_per_turn)} |",
        f"| Compaction events | {context.estimated_compaction_count} |",
        "",
        "### Context Curve",
        "",
        "```",
        _render_context_curve(context),
        "```",
        "",
    ]

    # Compaction events table
    if context.compaction_events:
        lines.append("### Compaction Events")
        lines.append("")
        lines.append("| Turn | Before | After | Tokens Lost |")
        lines.append("|------|--------|-------|-------------|")
        for event in context.compaction_events:
            lines.append(
                f"| {event.turn_number} | "
                f"{_format_tokens(event.tokens_before)} | "
                f"{_format_tokens(event.tokens_after)} | "
                f"{_format_tokens(event.estimated_tokens_lost)} |"
            )
        lines.append("")

    return "\n".join(lines)


def _priority_badge(priority: str) -> str:
    """Format a priority as a badge."""
    return f"[{priority.upper()}]"


def _render_suggestions(suggestions: SuggestionsReport) -> str:
    """Render Section 4: Suggestions."""
    lines = [
        "## 4. CLAUDE.md Suggestions",
        "",
    ]

    if not suggestions.suggestions:
        lines.append("No suggestions for this session.")
        lines.append("")
    else:
        for s in suggestions.suggestions:
            lines.append(f"- {_priority_badge(s.priority)} {s.suggestion}")
            lines.append(f"  - *Evidence: {s.evidence}*")
        lines.append("")

    # Top accessed files table
    if suggestions.top_accessed_files:
        lines.append("### Top Accessed Files")
        lines.append("")
        lines.append("| File | Reads | Edits | Writes | Total |")
        lines.append("|------|-------|-------|--------|-------|")
        for f in suggestions.top_accessed_files:
            lines.append(
                f"| `{f.file_path}` | {f.read_count} | "
                f"{f.edit_count} | {f.write_count} | {f.total} |"
            )
        lines.append("")

    return "\n".join(lines)
