"""Render accepted artifacts into public-safe Markdown drafts."""

from __future__ import annotations

import re
from datetime import date, datetime
from pathlib import Path

from aide.artifacts import get_artifact, list_artifacts

LOG_ARTIFACT_TYPES = frozenset({
    "agent_mistake",
    "decision",
    "future_agent_instruction",
    "planner_signal",
    "risky_action",
    "verification_recipe",
})
POST_DRAFT_ARTIFACT_TYPES = frozenset({
    "agent_mistake",
    "credential_step",
    "decision",
    "future_agent_instruction",
    "planner_signal",
    "risky_action",
    "setup_step",
    "verification_recipe",
})


def render_log_from_artifact(db_path: Path, artifact_id: int) -> str:
    """Render one accepted artifact as a website log entry."""
    artifact = _load_publishable_artifact(db_path, artifact_id)
    event_date = _artifact_date(artifact)
    description = _description(artifact["body"])
    source = _source_label(artifact)

    lines = [
        "---",
        "layout: page",
        f'title: "{_front_matter_escape(artifact["title"])}"',
        f"date: {event_date}",
        f'description: "{_front_matter_escape(description)}"',
        "---",
        "",
        f"*{event_date}*",
        "",
        artifact["body"].strip(),
        "",
    ]

    if source:
        lines.extend([
            f"Source: accepted aide artifact #{artifact['id']} from `{source}`.",
            "",
        ])

    lines.append(_closing_lesson(artifact))
    lines.append("")
    return "\n".join(lines)


def write_log_from_artifact(
    db_path: Path,
    artifact_id: int,
    output_path: Path,
    *,
    overwrite: bool = False,
) -> Path:
    """Write one accepted artifact as a website log entry."""
    if output_path.exists() and not overwrite:
        raise FileExistsError(f"Output already exists: {output_path}")
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(render_log_from_artifact(db_path, artifact_id))
    return output_path


def list_log_artifacts(
    db_path: Path,
    project_name: str,
    *,
    since: date | None = None,
) -> list[dict]:
    """List accepted artifacts that can be exported as public logs."""
    artifacts = []
    for row in list_artifacts(db_path, project_name=project_name, status="accepted"):
        if row["artifact_type"] not in LOG_ARTIFACT_TYPES:
            continue
        if since is not None and _artifact_date_value(row) < since:
            continue
        artifact = get_artifact(db_path, row["id"])
        if artifact is not None:
            artifacts.append(artifact)
    artifacts.sort(key=lambda item: (_artifact_date_value(item), item["id"]))
    return artifacts


def write_logs_for_project(
    db_path: Path,
    project_name: str,
    output_dir: Path,
    *,
    since: date | None = None,
    overwrite: bool = False,
) -> list[Path]:
    """Write publishable accepted artifacts for one project into a log directory."""
    output_paths = []
    for artifact in list_log_artifacts(db_path, project_name, since=since):
        output_path = output_dir / _log_filename(artifact)
        write_log_from_artifact(
            db_path,
            int(artifact["id"]),
            output_path,
            overwrite=overwrite,
        )
        output_paths.append(output_path)
    return output_paths


def render_post_draft(
    db_path: Path,
    project_name: str,
    topic: str,
    *,
    since: date | None = None,
) -> str:
    """Render a human-review post draft from accepted artifacts."""
    artifacts = _accepted_post_artifacts(db_path, project_name, since=since)
    today = datetime.now().date().isoformat()
    title = topic.strip()
    description = (
        f"Draft source map for {project_name} artifacts related to {title}."
    )

    lines = [
        "---",
        "layout: post",
        f'title: "{_front_matter_escape(title)}"',
        f"date: {today}",
        f'description: "{_front_matter_escape(description)}"',
        "---",
        "",
        "<!--",
        "Generated by aide from accepted semantic artifacts.",
        "Review, restructure, and remove private context before publishing.",
        "-->",
        "",
        "## Working Thesis",
        "",
        f"TODO: Turn the `{project_name}` evidence below into a clear argument about {topic}.",
        "",
        "## Possible Arc",
        "",
        "1. Context: what problem or pressure made this worth noticing.",
        "2. Evidence: the concrete incidents, decisions, or verification results.",
        "3. Interpretation: what changed in the operating model.",
        "4. Takeaway: the rule another engineer could apply.",
        "",
        "## Source Artifacts",
        "",
    ]

    if not artifacts:
        lines.extend([
            "No accepted artifacts found for this project.",
            "",
        ])
        return "\n".join(lines)

    by_type: dict[str, list[dict]] = {}
    for artifact in artifacts:
        by_type.setdefault(artifact["artifact_type"], []).append(artifact)

    for artifact_type in sorted(by_type):
        lines.append(f"### {artifact_type.replace('_', ' ').title()}")
        lines.append("")
        for artifact in by_type[artifact_type]:
            source = _source_label(artifact)
            source_text = f" Source: `{source}`." if source else ""
            lines.append(
                f"- Artifact #{artifact['id']} - {artifact['title']}: "
                f"{artifact['body']}{source_text}"
            )
        lines.append("")

    lines.extend([
        "## Open Questions",
        "",
        "- TODO: What evidence is missing?",
        "- TODO: Which details are private or too operational for publishing?",
        "- TODO: What examples make the post useful beyond this project?",
        "",
    ])
    return "\n".join(lines)


def write_post_draft(
    db_path: Path,
    project_name: str,
    topic: str,
    output_path: Path,
    *,
    since: date | None = None,
    overwrite: bool = False,
) -> Path:
    """Write a human-review post draft from accepted artifacts."""
    if output_path.exists() and not overwrite:
        raise FileExistsError(f"Output already exists: {output_path}")
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        render_post_draft(db_path, project_name, topic, since=since)
    )
    return output_path


def post_draft_filename(topic: str) -> str:
    """Return the deterministic draft filename for a topic."""
    return f"{_slugify(topic)}.md"


def log_filename_for_artifact(db_path: Path, artifact_id: int) -> str:
    """Return the deterministic log filename for one artifact."""
    artifact = _load_publishable_artifact(db_path, artifact_id)
    return _log_filename(artifact)


def _load_publishable_artifact(db_path: Path, artifact_id: int) -> dict:
    artifact = get_artifact(db_path, artifact_id)
    if artifact is None:
        raise ValueError(f"Artifact not found: {artifact_id}")
    if artifact["status"] != "accepted":
        raise ValueError("only accepted artifacts can be published")
    if artifact["artifact_type"] not in LOG_ARTIFACT_TYPES:
        raise ValueError(
            f"artifact type is not publishable as a log: {artifact['artifact_type']}"
        )
    return artifact


def _accepted_post_artifacts(
    db_path: Path,
    project_name: str,
    *,
    since: date | None = None,
) -> list[dict]:
    artifacts = []
    for row in list_artifacts(db_path, project_name=project_name, status="accepted"):
        if row["artifact_type"] not in POST_DRAFT_ARTIFACT_TYPES:
            continue
        if since is not None and _artifact_date_value(row) < since:
            continue
        artifact = get_artifact(db_path, row["id"])
        if artifact is not None:
            artifacts.append(artifact)
    artifacts.sort(key=lambda item: (_artifact_date_value(item), item["artifact_type"], item["id"]))
    return artifacts


def _artifact_date(artifact: dict) -> str:
    return _artifact_date_value(artifact).isoformat()


def _artifact_date_value(artifact: dict) -> date:
    value = artifact.get("first_seen_at") or artifact.get("created_at")
    if not value:
        return datetime.now().date()
    return datetime.fromisoformat(str(value)).date()


def _description(body: str) -> str:
    text = " ".join(body.split())
    if len(text) <= 150:
        return text
    return text[:147].rstrip() + "..."


def _closing_lesson(artifact: dict) -> str:
    artifact_type = artifact["artifact_type"]
    if artifact_type == "verification_recipe":
        return "The reusable rule is to keep proven verification commands close to future work."
    if artifact_type == "agent_mistake":
        return (
            "The reusable rule is to turn repeated agent failure modes into "
            "explicit future-agent guidance."
        )
    if artifact_type == "risky_action":
        return "The reusable rule is to make risky actions explicit before they become routine."
    if artifact_type == "decision":
        return (
            "The reusable rule is to record the decision with the evidence that "
            "made it worth keeping."
        )
    if artifact_type == "planner_signal":
        return (
            "The reusable rule is to preserve planning signals while the context "
            "is still fresh."
        )
    return "The reusable rule is to convert accepted session evidence into durable project memory."


def _log_filename(artifact: dict) -> str:
    return f"{_slugify(artifact['title'])}.md"


def _source_label(artifact: dict) -> str | None:
    provider = artifact.get("source_provider")
    session_id = artifact.get("source_session_id")
    if not provider or not session_id:
        return None
    return f"{provider}:{session_id}"


def _slugify(value: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")
    return slug or "aide-log"


def _front_matter_escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')
